version: "3.7"

services:
  controller001:
    build:
      context: .
      dockerfile: kafka.Dockerfile
    image: kazono/kafka-kraft:3.6.1
    hostname: controller001
    container_name: controller001
    environment:
      KAFKA_PROCESS_ROLES: controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1\@controller001:9093,2\@controller002:9093,3\@controller003:9093
      # settings for SASL/SSL (PLAIN)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_SSL
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
      KAFKA_LISTENER_NAME_CONTROLLER_PLAIN_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret" user_admin="admin-secret";
      # settings for SSL/TLS communication
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/private/ssl/server.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: changeit
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/private/ssl/server.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_SSL_KEY_PASSWORD: changeit
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
      KAFKA_SSL_SECURE_RANDOM_IMPLEMENTATION: SHA1PRNG
      KAFKA_LISTENER_NAME_CONTROLLER_SSL_CLIENT_AUTH: required
      # settings for authorizer
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_SUPER_USERS: User:admin
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true
  controller002:
    build:
      context: .
      dockerfile: kafka.Dockerfile
    image: kazono/kafka-kraft:3.6.1
    hostname: controller002
    container_name: controller002
    environment:
      KAFKA_PROCESS_ROLES: controller
      KAFKA_NODE_ID: 2
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1\@controller001:9093,2\@controller002:9093,3\@controller003:9093
      # settings for SASL/SSL (PLAIN)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_SSL
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
      KAFKA_LISTENER_NAME_CONTROLLER_PLAIN_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret" user_admin="admin-secret";
      # settings for SSL/TLS communication
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/private/ssl/server.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: changeit
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/private/ssl/server.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_SSL_KEY_PASSWORD: changeit
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
      KAFKA_SSL_SECURE_RANDOM_IMPLEMENTATION: SHA1PRNG
      KAFKA_LISTENER_NAME_CONTROLLER_SSL_CLIENT_AUTH: required
      # settings for authorizer
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_SUPER_USERS: User:admin
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true
  controller003:
    build:
      context: .
      dockerfile: kafka.Dockerfile
    image: kazono/kafka-kraft:3.6.1
    hostname: controller003
    container_name: controller003
    environment:
      KAFKA_PROCESS_ROLES: controller
      KAFKA_NODE_ID: 3
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1\@controller001:9093,2\@controller002:9093,3\@controller003:9093
      # settings for SASL/SSL (PLAIN)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_SSL
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
      KAFKA_LISTENER_NAME_CONTROLLER_PLAIN_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret" user_admin="admin-secret";
      # settings for SSL/TLS communication
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/private/ssl/server.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: changeit
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/private/ssl/server.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_SSL_KEY_PASSWORD: changeit
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
      KAFKA_SSL_SECURE_RANDOM_IMPLEMENTATION: SHA1PRNG
      KAFKA_LISTENER_NAME_CONTROLLER_SSL_CLIENT_AUTH: required
      # settings for authorizer
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_SUPER_USERS: User:admin
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true

  broker001:
    build:
      context: .
      dockerfile: kafka.Dockerfile
    image: kazono/kafka-kraft:3.6.1
    hostname: broker001
    container_name: broker001
    depends_on:
      - controller001
      - controller002
      - controller003
    environment:
      KAFKA_PROCESS_ROLES: broker
      KAFKA_NODE_ID: 4
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1\@controller001:9093,2\@controller002:9093,3\@controller003:9093
      KAFKA_LISTENERS: BROKER_PLAINTEXT://broker001:9091,BROKER_SASL_SSL://broker001:9092
      KAFKA_ADVERTISED_LISTENERS: BROKER_PLAINTEXT://broker001:9091,BROKER_SASL_SSL://broker001:9092
      # settings for SASL/SSL (SCRAM)
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER_SASL_SSL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER_SASL_SSL:SASL_SSL,BROKER_PLAINTEXT:PLAINTEXT,CONTROLLER:SASL_SSL
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
      KAFKA_LISTENER_NAME_CONTROLLER_PLAIN_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret" user_admin="admin-secret";
      # settings for SSL/TLS communication
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/private/ssl/server.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: changeit
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/private/ssl/server.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_SSL_KEY_PASSWORD: changeit
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
      KAFKA_SSL_SECURE_RANDOM_IMPLEMENTATION: SHA1PRNG
      # settings for authorizer
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_SUPER_USERS: User:admin
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true
      KAFKA_OPTS: -Djava.security.auth.login.config=/opt/kafka/config/kafka_jaas.conf
    volumes:
      - ./files/props/admin.properties:/opt/kafka/config/admin.properties
      - ./files/jaas/kafka_jaas.conf:/opt/kafka/config/kafka_jaas.conf
  broker002:
    build:
      context: .
      dockerfile: kafka.Dockerfile
    image: kazono/kafka-kraft:3.6.1
    hostname: broker002
    container_name: broker002
    depends_on:
      - controller001
      - controller002
      - controller003
    environment:
      KAFKA_PROCESS_ROLES: broker
      KAFKA_NODE_ID: 5
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1\@controller001:9093,2\@controller002:9093,3\@controller003:9093
      KAFKA_LISTENERS: BROKER_PLAINTEXT://broker002:9091,BROKER_SASL_SSL://broker002:9092
      KAFKA_ADVERTISED_LISTENERS: BROKER_PLAINTEXT://broker002:9091,BROKER_SASL_SSL://broker002:9092
      # settings for SASL/SSL (SCRAM)
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER_SASL_SSL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER_SASL_SSL:SASL_SSL,BROKER_PLAINTEXT:PLAINTEXT,CONTROLLER:SASL_SSL
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
      KAFKA_LISTENER_NAME_CONTROLLER_PLAIN_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret" user_admin="admin-secret";
      # settings for SSL/TLS communication
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/private/ssl/server.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: changeit
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/private/ssl/server.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_SSL_KEY_PASSWORD: changeit
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
      KAFKA_SSL_SECURE_RANDOM_IMPLEMENTATION: SHA1PRNG
      # settings for authorizer
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_SUPER_USERS: User:admin
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true
      KAFKA_OPTS: -Djava.security.auth.login.config=/opt/kafka/config/kafka_jaas.conf
    volumes:
      - ./files/props/admin.properties:/opt/kafka/config/admin.properties
      - ./files/jaas/kafka_jaas.conf:/opt/kafka/config/kafka_jaas.conf
  broker003:
    build:
      context: .
      dockerfile: kafka.Dockerfile
    image: kazono/kafka-kraft:3.6.1
    hostname: broker003
    container_name: broker003
    depends_on:
      - controller001
      - controller002
      - controller003
    environment:
      KAFKA_PROCESS_ROLES: broker
      KAFKA_NODE_ID: 6
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1\@controller001:9093,2\@controller002:9093,3\@controller003:9093
      KAFKA_LISTENERS: BROKER_PLAINTEXT://broker003:9091,BROKER_SASL_SSL://broker003:9092
      KAFKA_ADVERTISED_LISTENERS: BROKER_PLAINTEXT://broker003:9091,BROKER_SASL_SSL://broker003:9092
      # settings for SASL/SSL (SCRAM)
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER_SASL_SSL
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER_SASL_SSL:SASL_SSL,BROKER_PLAINTEXT:PLAINTEXT,CONTROLLER:SASL_SSL
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-256
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-256
      KAFKA_LISTENER_NAME_CONTROLLER_PLAIN_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret" user_admin="admin-secret";
      # settings for SSL/TLS communication
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/private/ssl/server.truststore.jks
      KAFKA_SSL_TRUSTSTORE_PASSWORD: changeit
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/private/ssl/server.keystore.jks
      KAFKA_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_SSL_KEY_PASSWORD: changeit
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
      KAFKA_SSL_SECURE_RANDOM_IMPLEMENTATION: SHA1PRNG
      # settings for authorizer
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_SUPER_USERS: User:admin
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: true
      KAFKA_OPTS: -Djava.security.auth.login.config=/opt/kafka/config/kafka_jaas.conf
    volumes:
      - ./files/props/admin.properties:/opt/kafka/config/admin.properties
      - ./files/jaas/kafka_jaas.conf:/opt/kafka/config/kafka_jaas.conf

  cli:
    build:
      context: .
      dockerfile: kafka.Dockerfile
    image: kazono/kafka-kraft:3.6.1
    hostname: cli
    container_name: cli
    tty: true
    volumes:
      - ./files/props/client.properties:/opt/kafka/config/client.properties

  terraform-cli:
    build:
      context: .
      dockerfile: terraform.Dockerfile
    image: kazono/terraform:1.5.7
    hostname: terraform-cli
    container_name: terraform-cli
    tty: true
    volumes:
      - ./samples/terraform:/root/sample
      - ./files/certs/root-ca/ca.crt:/tmp/ca.crt
      - ./files/certs/terraform/terraform-client.crt:/tmp/terraform-client.crt
      - ./files/certs/terraform/terraform-client.key:/tmp/terraform-client.key

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - broker001
      - broker002
      - broker003
    environment:
      TZ: Asia/Tokyo
      # settings for access brokers using PLAINTEXT
      KAFKA_CLUSTERS_0_NAME: via-plaintext-port
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker001:9091,broker002:9091,broker003:9091
      # settings for access brokers using SASL/SSL (SCRAM)
      KAFKA_CLUSTERS_1_NAME: via-sasl-ssl-port
      KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS: broker001:9092,broker002:9092,broker003:9092
      KAFKA_CLUSTERS_1_PROPERTIES_SECURITY_PROTOCOL: SASL_SSL
      KAFKA_CLUSTERS_1_PROPERTIES_SASL_MECHANISM: SCRAM-SHA-256
      KAFKA_CLUSTERS_1_PROPERTIES_SASL_JAAS_CONFIG: org.apache.kafka.common.security.scram.ScramLoginModule required username='admin' password='admin-secret';
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_KEYSTORE_LOCATION: /server.keystore.jks
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_KEYSTORE_PASSWORD: changeit
      KAFKA_CLUSTERS_1_SSL_TRUSTSTORELOCATION: /server.truststore.jks
      KAFKA_CLUSTERS_1_SSL_TRUSTSTOREPASSWORD: changeit
      KAFKA_CLUSTERS_1_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
    volumes:
      - ./files/certs/kafka-ui/server.keystore.jks:/server.keystore.jks
      - ./files/certs/kafka-ui/server.truststore.jks:/server.truststore.jks

networks:
  default:
    name: dev.local.co.jp
